
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(ac17dea1-2710-4a87-b16f-88ff9a3b5bec)'
    subscriptionId: 'ac17dea1-2710-4a87-b16f-88ff9a3b5bec'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rgdev'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/template.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/parameters.json'
    deploymentMode: 'Incremental'
